# Generated by Django 5.0.6 on 2024-06-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('business', 'ビジネス'), ('life', '生活'), ('novel', '小誌'), ('fiction', '文学'), ('romance', '恋愛'), ('fantasy', 'ファンタジー'), ('mystery', 'ミステリー'), ('historical', '歴史'), ('other', 'その他')], max_length=100),
        ),
    ]
